#!/bin/sh
SCRIPTPATH=$(dirname "$0")
CLASSPATH="$SCRIPTPATH":"$SCRIPTPATH"/bin/:"$SCRIPTPATH"/dist/\*:"$SCRIPTPATH"/lib/\*
java -Xmx2048m -Xss1m -cp "$CLASSPATH" \
	edu.northwestern.at.morphadorner.MorphAdorner \
	-p ncfa.properties \
	-l data/ncflexicon.lex \
	-t data/ncftransmat.mat \
	-u data/ncfsuffixlexicon.lex \
	-a data/ncfmergedspellingpairs.tab \
	-s data/standardspellings.txt \
	-w data/spellingsbywordclass.txt \
	-o "$1" \
	"$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
