#!/bin/sh
SCRIPTPATH=$(dirname "$0")
CLASSPATH="$SCRIPTPATH":"$SCRIPTPATH"/bin/:"$SCRIPTPATH"/dist/\*:"$SCRIPTPATH"/lib/\*
java -Xmx4096m -Xss1m -cp "$CLASSPATH" \
	edu.northwestern.at.morphadorner.tools.createlexicon.CreateLexicon \
	"$1" "$2" "$3" $4 $5 $6 $7 $8 $9

