#!/bin/sh
java -Xmx1024m -Xss1m -cp .:bin/:dist/* \
	edu.northwestern.at.morphadorner.tools.fixquotes.fixquotes.FixXMLQuotes \
	data\softtags.txt data\jumptags.txt \
	"$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
