#!/bin/sh
SCRIPTPATH=$(dirname "$0")
CLASSPATH="$SCRIPTPATH":"$SCRIPTPATH"/bin/:"$SCRIPTPATH"/dist/\*:lib/\*
java -cp "$CLASSPATH"  edu.northwestern.at.morphadorner.tools.lgparser.LGParser \
	"$SCRIPTPATH"/data/lgparser "$1"
