#!/bin/sh
SCRIPTPATH=$(dirname "$0")
CLASSPATH="$SCRIPTPATH":"$SCRIPTPATH"/bin/:"$SCRIPTPATH"/dist/\*:lib/\*
java -Xmx2048m -Xss1m -cp "$CLASSPATH" \
	edu.northwestern.at.morphadorner.tools.mergebrilllexicon.MergeBrillLexicon \
	"$1" "$2" "$3"

