#!/bin/sh
SCRIPTPATH=$(dirname "$0")
CLASSPATH="$SCRIPTPATH":"$SCRIPTPATH"/bin/:"$SCRIPTPATH"/dist/\*:"$SCRIPTPATH"/lib/\*
java -Xmx2048m -Xss1m -cp "$CLASSPATH" \
	edu.northwestern.at.morphadorner.tools.applyxslt.ApplyXSLT \
	"$1" xslt/movenotes.xsl "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
