#!/bin/sh
SCRIPTPATH=$(dirname "$0")
CLASSPATH="$SCRIPTPATH":"$SCRIPTPATH"/bin/:"$SCRIPTPATH"/dist/\*:"$SCRIPTPATH"/lib/\*
java -Xmx2048m -Xss1m -cp "$CLASSPATH" \
	edu.northwestern.at.morphadorner.tools.relemmatize.Relemmatize \
	data/emelexicon.lex \
	data/ememergedspellingpairs.tab \
	data/spellingsbywordclass.txt  \
	data/standardspellings.txt  \
	"$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"

