#!/bin/sh
SCRIPTPATH=$(dirname "$0")
CLASSPATH="$SCRIPTPATH":"$SCRIPTPATH"/bin/:"$SCRIPTPATH"/dist/\*:"$SCRIPTPATH"/lib/\*
java -Xmx2048m -Xss1m -cp "$CLASSPATH" \
lib/icu4j-charsets_3_6_1.jar:lib/icu4j_3_6_1.jar:\
lib\isorelax.jar:lib\isorelax-jaxp-bridge-1.0.jar:\
lib\msv.jar:lib\relaxngDatatype.jar:lib\xsdlib.jar \
	edu.northwestern.at.morphadorner.tools.relemmatize.Relemmatize \
	"$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"

