#!/bin/sh
java -Xmx2048m -Xss1m -cp .:bin/:dist/*:lib/* \
	edu.northwestern.at.morphadorner.tools.relemmatize.Relemmatize  \
	data/ncflexicon.lex \
	data/ncfmergedspellingpairs.tab \
	data/spellingsbywordclass.txt  \
	data/standardspellings.txt  \
	"$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"

