#!/bin/sh
SCRIPTPATH=$(dirname "$0")
CLASSPATH="$SCRIPTPATH":"$SCRIPTPATH"/bin/:"$SCRIPTPATH"/dist/\*:"$SCRIPTPATH"/lib/\*
java -Xmx4g -Xss1m -cp "$CLASSPATH" \
	edu.northwestern.at.morphadorner.tools.xmltotab.AdornedToTabularFile "$1" "$2"
